const express = require('express');
const crypto = require('crypto');
const { createChatCompletion, getDeepSeekModel } = require('../utils/deepseekClient');

const JOB_TTL_MS = 30 * 60 * 1000;
const JOB_CLEANUP_INTERVAL_MS = 10 * 60 * 1000;
const jobs = new Map();

function createJobId() {
  if (crypto.randomUUID) {
    return crypto.randomUUID();
  }
  return `reschedule_${Date.now()}_${crypto.randomBytes(8).toString('hex')}`;
}

function now() {
  return Date.now();
}

function toStatusPayload(job) {
  return {
    jobId: job.jobId,
    status: job.status,
    phase: job.phase,
    message: job.message,
    current: job.current,
    total: job.total,
    percent: job.percent,
    result: job.result,
    error: job.error,
    createdAt: job.createdAt,
    updatedAt: job.updatedAt
  };
}

function updateJob(jobId, patch) {
  const job = jobs.get(jobId);
  if (!job) {
    return;
  }
  Object.assign(job, patch, { updatedAt: now() });
}

function parseTaskSummary(summaryText) {
  try {
    const parsed = JSON.parse(summaryText || '[]');
    return Array.isArray(parsed) ? parsed : [];
  } catch (_) {
    return [];
  }
}

function buildReschedulePrompt(overdueTasksSummary, futureTasksSummary) {
  const currentDate = new Date().toISOString().split('T')[0];
  return `
你是一名专业的时间管理与拖延症恢复教练。用户积压了若干未完成任务，请根据每个任务的优先级、预估耗时、历史延期次数和逾期状态，帮用户分组整理，制定一份克制、温和的恢复计划。

当前日期：${currentDate}

【核心原则】
- 偏克制，默认采取暂缓或顺延
- 【全量覆盖】积压任务清单中每一个 isOverdue=true 的任务 id 都必须且只能出现在 6 个输出分组中的一个，不能只处理部分任务，也不能遗漏任务。
- 【明天容量限制】tomorrowTasks 最多 6 项，且总预估耗时不应超过 2 小时。不要把大量积压任务推给明天，否则会造成二次逾期。
- 【重要】必须参考“未来几天已有任务”和每个任务的 similarTaskKey / sameTypeFutureDates，避免将同类或相似任务（如运动、阅读、饮食记录、体重记录等习惯）重排到已经安排了相似任务的日期。如果目标日期已有类似任务，请安排到其他日期，或建议暂缓。
- 【目标内去重】相似任务的删除、错峰和去重只允许在同一个 goalId / goalTitle 内判断。跨目标即使标题相似，也不能作为 deleteTasks、shelveTasks 或降级的依据；跨目标任务只用于判断当天总负载，不用于同类删除。
- 【任务来源规则】必须区分任务来源。若 sourceType="auto_periodic_reminder"，或 isReminderAutoGenerated=true 且 reminderEventType="periodic"，默认放入 deleteTasks，理由说明“周期提醒生成的过期任务通常无需补做，删除不会影响后续提醒”。不要把这类任务安排到明天或本周稍后，除非任务标题明确表示必须补做。
- 【周期任务规则】特别是 reminderRuleTypes 包含 periodic_daily / habit_daily 的逾期任务，错过后通常无法补做，应放入 deleteTasks。
- 【同源周期错峰】如果多条积压任务来自同一个周期任务来源（同一个 reminderId / similarTaskKey），即使决定保留，也必须分散到不同日期，绝不能排到同一天；同一来源最多只允许 1 条进入 tomorrowTasks，其余必须继续顺延、暂缓或删除。
- 【习惯任务规则】如果 reminderEventType="habit"，或标题明显是习惯养成/每日记录/打卡类任务，逾期未做一般不补做；如确实需要保留，必须安排到 sameTypeFutureDates 中最后一个同类日期之后，且同一天只能有一个同类任务。
- 【依赖顺序规则】必须识别任务标题、description、goalTitle、krTitle、subtaskTitles 和 possiblePrerequisites 中的前后依赖。如果 B 需要 A 完成后才能开始，必须把 A 排在 B 前面；A 可进入 tomorrowTasks 或更早的 thisWeekTasks，B 必须延期到 A 之后，或暂缓。典型例子：“记录今日体脂率”依赖“购买体脂秤”，必须先安排购买体脂秤，再安排记录体脂率，不能反过来。
- 【去重规则】同一个 similarTaskKey 在同一天最多只能安排一次。重复的同类任务应错峰、暂缓或删除，绝不能全部放入 tomorrowTasks。
- 【删除规则】如果某项任务在未来完全没有合适的插入时间，或是错过即失效的日常循环任务，建议直接删除（放入 deleteTasks 中），我们将询问用户是否确认删除。

请将任务分为以下6个分组，严格输出纯 JSON：

1. \`tomorrowTasks\`: 建议保留到明天的任务（最多 6 项；高优、短耗时、必须接住，且明天没有相似冲突任务）
2. \`thisWeekTasks\`: 建议安排到本周稍后的任务（重要但不紧迫），建议日期 newDate（必须避开已有相似任务的日期，同类任务必须错峰）
3. \`downgradeTasks\`: 建议降低优先级的任务（长期积压、多次延期但非核心）
4. \`splitTasks\`: 建议拆分的大颗粒度任务（预估耗时长 >= 2h），提供拆分后的子任务标题
5. \`shelveTasks\`: 建议暂缓/搁置的任务（多次延期且低优，或近期每天都有类似任务排不开），注意不是删除，语意为"暂时搁置"
6. \`deleteTasks\`: 建议直接删除/放弃的任务（未来无合适插入时间、已失去时效性，或每日/周期类过期任务无法补做）

输出格式：
{
  "tomorrowTasks": [{ "id": "taskId", "reason": "已逾期且仅需10分钟" }],
  "thisWeekTasks": [{ "id": "taskId", "newDate": "${currentDate}", "reason": "重要但今天精力不足" }],
  "downgradeTasks": [{ "id": "taskId", "reason": "已延期3次，非核心事项" }],
  "splitTasks": [{ "id": "taskId", "subTasks": ["子任务1", "子任务2"], "reason": "耗时太长建议拆细" }],
  "shelveTasks": [{ "id": "taskId", "reason": "低优且多次延期，建议暂时搁置" }],
  "deleteTasks": [{ "id": "taskId", "reason": "近期排不开且已无时效性，建议删除" }],
  "summary": "简洁一句话总结本次重排方案"
}

积压任务清单：
${overdueTasksSummary}

未来几天已有任务（重排请尽力避开高度相似冲突的任务时间）：
${futureTasksSummary ? futureTasksSummary : '无'}
`;
}

function extractCompletionText(data) {
  if (data?.output?.text) {
    return data.output.text;
  }
  if (data?.output?.choices?.[0]?.message?.content) {
    return data.output.choices[0].message.content;
  }
  return '';
}

function parseJsonFromText(text) {
  let content = String(text || '').replace(/```json/gi, '').replace(/```/g, '').trim();
  const startIdx = content.indexOf('{');
  const endIdx = content.lastIndexOf('}');
  if (startIdx >= 0 && endIdx >= startIdx) {
    content = content.substring(startIdx, endIdx + 1);
  }
  return JSON.parse(content);
}

async function recordTokenUsage(deps, userId, usageData) {
  if (!usageData || !userId) {
    return;
  }

  const inputTokens = usageData.prompt_tokens || usageData.input_tokens || 0;
  const outputTokens = usageData.completion_tokens || usageData.output_tokens || 0;
  const totalTokens = usageData.total_tokens || (inputTokens + outputTokens);
  const modelId = usageData.model || '';
  const yearMonth = deps.usageRoutes.getCurrentYearMonth();

  const record = new deps.UsageRecord({
    userId,
    type: 'token',
    amount: totalTokens,
    detail: { inputTokens, outputTokens, model: modelId },
    yearMonth,
    createdAt: Date.now()
  });
  await record.save();
  await deps.usageRoutes.updateMonthlySummary(userId, 'token', totalTokens, { inputTokens, outputTokens });
}

async function runRescheduleJob(jobId, payload, deps) {
  const job = jobs.get(jobId);
  if (!job) {
    return;
  }

  try {
    const overdueTasks = parseTaskSummary(payload.overdueTasksSummary);
    const total = Math.max(1, payload.totalTasks || overdueTasks.length);
    updateJob(jobId, {
      status: 'running',
      phase: 'preparing',
      message: '正在校验积压任务',
      current: 0,
      total,
      percent: 5
    });

    overdueTasks.forEach((_, index) => {
      const current = Math.min(total, index + 1);
      updateJob(jobId, {
        current,
        percent: Math.min(45, 5 + Math.floor((current / total) * 40))
      });
    });

    updateJob(jobId, {
      phase: 'context',
      message: '正在构建任务上下文',
      current: total,
      total,
      percent: 50
    });

    const prompt = buildReschedulePrompt(payload.overdueTasksSummary, payload.futureTasksSummary);
    updateJob(jobId, {
      phase: 'ai_generating',
      message: 'AI 正在生成恢复方案',
      current: total,
      total,
      percent: 70
    });

    const completion = await createChatCompletion({
      model: getDeepSeekModel(payload.model || process.env.AGENT_RESCHEDULE_MODEL || process.env.DEEPSEEK_FAST_MODEL || process.env.DEEPSEEK_MODEL || 'deepseek-v4-flash'),
      timeoutMs: 120000,
      temperature: 0.2,
      thinking: 'disabled',
      traceLabel: 'agent.reschedule',
      messages: [
        {
          role: 'system',
          content: '你是四时清单的任务重排助手。只输出纯 JSON，不要输出 markdown 或解释。'
        },
        {
          role: 'user',
          content: prompt
        }
      ]
    });

    updateJob(jobId, {
      phase: 'parsing',
      message: '正在解析并校验建议',
      current: total,
      total,
      percent: 90
    });

    const content = completion.content;
    if (!content) {
      throw new Error('AI 未返回有效内容');
    }
    const result = parseJsonFromText(content);

    recordTokenUsage(deps, payload.userId, {
      ...(completion.data?.usage || {}),
      model: completion.data?.model || completion.model
    })
      .catch(error => console.warn('Token 用量自动记录异常:', error.message));

    updateJob(jobId, {
      status: 'completed',
      phase: 'completed',
      message: '重排建议已生成',
      current: total,
      total,
      percent: 100,
      result
    });
  } catch (error) {
    const responseData = error.response?.data;
    const status = error.response?.status;
    const isQuotaError = status === 402 || status === 429 ||
      (responseData?.code && /QuotaExceeded|Throttling|OutOfBalance|Forbidden/i.test(responseData.code));
    const errorMessage = isQuotaError
      ? '云端 AI 额度暂时耗尽或服务拥挤，请稍后再试'
      : (error.message || 'AI 重排失败');
    updateJob(jobId, {
      status: 'failed',
      phase: 'failed',
      message: errorMessage,
      error: errorMessage,
      percent: Math.max(job.percent || 0, 70)
    });
  }
}

function cleanupJobs() {
  const cutoff = now() - JOB_TTL_MS;
  for (const [jobId, job] of jobs.entries()) {
    if (job.updatedAt < cutoff) {
      jobs.delete(jobId);
    }
  }
}

setInterval(cleanupJobs, JOB_CLEANUP_INTERVAL_MS);

module.exports = function createAgentRescheduleRouter(deps) {
  const router = express.Router();

  router.post('/start', (req, res) => {
    const totalTasks = Number(req.body?.totalTasks || 0);
    const overdueTasksSummary = String(req.body?.overdueTasksSummary || '[]');
    const futureTasksSummary = String(req.body?.futureTasksSummary || '[]');
    const jobId = createJobId();
    const userId = req.user?.userId || req.user?.id || 'anonymous';
    const job = {
      jobId,
      userId,
      status: 'queued',
      phase: 'queued',
      message: '等待开始',
      current: 0,
      total: Math.max(1, totalTasks),
      percent: 0,
      result: undefined,
      error: undefined,
      createdAt: now(),
      updatedAt: now()
    };
    jobs.set(jobId, job);

    setImmediate(() => {
      runRescheduleJob(jobId, {
        userId,
        overdueTasksSummary,
        futureTasksSummary,
        totalTasks,
        appId: req.body?.app_id
      }, deps);
    });

    res.json({ success: true, data: toStatusPayload(job) });
  });

  router.get('/status/:jobId', (req, res) => {
    const job = jobs.get(req.params.jobId);
    const userId = req.user?.userId || req.user?.id || 'anonymous';
    if (!job || job.userId !== userId) {
      return res.status(404).json({ success: false, message: '任务不存在或已过期' });
    }
    res.json({ success: true, data: toStatusPayload(job) });
  });

  return router;
};
