export const TYPE_PAGE_TITLE: number = 23;
export const TYPE_HERO_TITLE: number = 19;
export const TYPE_SECTION_TITLE: number = 17;
export const TYPE_BODY: number = 15;
export const TYPE_META: number = 13;
export const TYPE_CAPTION: number = 12;
export const TYPE_NUMERIC_LG: number = 29;
export const TYPE_NUMERIC_MD: number = 23;

export const FONT_FAMILY_SC: string = '$rawfile(\'fonts/HarmonyOS_SansSC_Regular.ttf\')';
export const FONT_FAMILY_SC_MEDIUM: string = '$rawfile(\'fonts/HarmonyOS_SansSC_Medium.ttf\')';
export const FONT_FAMILY_SC_BOLD: string = '$rawfile(\'fonts/HarmonyOS_SansSC_Bold.ttf\')';
