export const TYPE_PAGE_TITLE: number = 22;
export const TYPE_HERO_TITLE: number = 18;
export const TYPE_SECTION_TITLE: number = 16;
export const TYPE_BODY: number = 14;
export const TYPE_META: number = 12;
export const TYPE_CAPTION: number = 11;
export const TYPE_MICRO: number = 11;
export const TYPE_NUMERIC_LG: number = 28;
export const TYPE_NUMERIC_MD: number = 22;
export const TYPE_DISPLAY_TIMER: number = 80;

export const FONT_FAMILY_SC: string = '$rawfile(\'fonts/HarmonyOS_SansSC_Regular.ttf\')';
export const FONT_FAMILY_SC_MEDIUM: string = '$rawfile(\'fonts/HarmonyOS_SansSC_Medium.ttf\')';
export const FONT_FAMILY_SC_BOLD: string = '$rawfile(\'fonts/HarmonyOS_SansSC_Bold.ttf\')';
