const mongoose = require('mongoose');

// ---- 子文档 Schema：为数组字段提供结构定义和验证 ----

const keyResultSchema = new mongoose.Schema({
  id: String,
  title: String,
  targetValue: Number,
  initialValue: Number,
  currentValue: Number,
  progress: Number,
  completed: Boolean,
  createdAt: Number,
  weight: Number
}, { _id: false });

const goalSchema = new mongoose.Schema({
  id: { type: String, required: true },
  title: String,
  description: String,
  category: String,
  keyResults: [keyResultSchema],
  progress: Number,
  startDate: Number,
  endDate: Number,
  createdAt: Number,
  updatedAt: { type: Number, index: true },
  isPriority: Boolean,
  isArchived: Boolean,
  archivedAt: Number
}, { _id: false });

const subtaskSchema = new mongoose.Schema({
  id: String,
  title: String,
  isCompleted: Boolean
}, { _id: false });

const taskSchema = new mongoose.Schema({
  id: { type: String, required: true },
  title: String,
  description: String,
  goalId: String,
  goalTitle: String,
  reminderId: String,
  reminderTitle: String,
  isReminderAutoGenerated: Boolean,
  reminderOccurrenceTime: Number,
  krId: String,
  krTitle: String,
  dueDate: Number,
  dueTime: String,
  priority: { type: String, enum: ['high', 'normal', 'low'], default: 'normal' },
  status: { type: String, enum: ['pending', 'completed'], default: 'pending' },
  createdAt: Number,
  completedAt: Number,
  updatedAt: { type: Number, index: true },
  isPinned: Boolean,
  pomodoroCount: Number,
  category: String,
  subtasks: [subtaskSchema],
  isImportant: Boolean,
  estimatedHours: Number,
  aiGenerated: Boolean,
  delayCount: Number
}, { _id: false });

const reminderRuleSchema = new mongoose.Schema({
  id: String,
  type: String,
  hour: Number,
  minute: Number,
  weekday: Number,
  dayOfMonth: Number,
  lastDayOffset: Number,
  intervalDays: Number,
  timesPerPeriod: Number,
  leadDays: Number,
  offsetValue: Number,
  offsetUnit: String,
  targetDate: Number
}, { _id: false });

const dayEventSchema = new mongoose.Schema({
  id: { type: String, required: true },
  title: String,
  type: String,
  startDate: Number,
  targetDate: Number,
  goalId: String,
  goalTitle: String,
  krId: String,
  krTitle: String,
  endDate: Number,
  reminderRules: [reminderRuleSchema],
  isEnabled: Boolean,
  isCompleted: Boolean,
  pausedUntil: Number,
  skipWeekends: Boolean,
  notificationMessage: String,
  createdAt: Number,
  updatedAt: { type: Number, index: true }
}, { _id: false });

const pomodoroSchema = new mongoose.Schema({
  id: { type: String, required: true },
  taskId: String,
  taskTitle: String,
  duration: Number,
  startTime: Number,
  endTime: Number,
  completed: Boolean,
  createdAt: Number,
  roundIndex: Number,
  totalRounds: Number,
  breakDuration: Number
}, { _id: false });

// ---- 主文档 Schema ----

const syncDataSchema = new mongoose.Schema({
  userId: { type: String, required: true, unique: true },
  goals: [goalSchema],
  tasks: [taskSchema],
  dayEvents: [dayEventSchema],
  pomodoros: [pomodoroSchema],
  updatedAt: { type: Number, default: () => Date.now() }
});

module.exports = mongoose.model('SyncData', syncDataSchema);
