/**
 * PlanScheduler — 每天凌晨3:00自动为活跃用户生成今日计划
 * 
 * 流程：
 * 1. 从 SyncData 中获取所有有任务数据的用户
 * 2. 筛选 status === 'pending' 的任务
 * 3. 去重：同一个 reminderId 只保留一条
 * 4. 调用百炼 AI 生成计划
 * 5. 存入 PreGeneratedPlan 集合
 */

const cron = require('node-cron');
const axios = require('axios');
const User = require('../models/User');
const SyncData = require('../models/SyncData');
const PreGeneratedPlan = require('../models/PreGeneratedPlan');
const { getShanghaiDateString } = require('../utils/date');

class PlanScheduler {
  constructor() {
    this.appId = process.env.ALIBABA_CLOUD_BAILIAN_APP_ID;
    this.apiKey = process.env.ALIBABA_CLOUD_BAILIAN_API_KEY;
  }

  /**
   * 启动定时任务
   */
  start() {
    // 每天凌晨2:30执行（服务器时区）
    cron.schedule('30 2 * * *', async () => {
      console.log('[PlanScheduler] 凌晨2:30定时任务触发，开始为高级用户预生成今日计划...');
      try {
        await this.generatePlansForAllUsers();
      } catch (error) {
        console.error('[PlanScheduler] 批量生成失败:', error.message);
      }
    }, {
      timezone: 'Asia/Shanghai'
    });

    console.log('[PlanScheduler] 定时任务已注册：每天凌晨2:30 (Asia/Shanghai)');
  }

  /**
   * 为所有活跃高级会员生成计划
   */
  async generatePlansForAllUsers() {
    const targetDate = getShanghaiDateString();
    
    // 查找所有高级会员
    const premiumUsers = await User.find({ membershipType: 'premium' });
    const premiumUserIds = premiumUsers.map(u => u.userId);

    // 查找这些高级会员同步的数据
    const allSyncData = await SyncData.find({ 
      userId: { $in: premiumUserIds },
      'tasks.0': { $exists: true } 
    });
    console.log(`[PlanScheduler] 找到 ${allSyncData.length} 个有任务数据的高级用户`);

    let successCount = 0;
    let skipCount = 0;
    let errorCount = 0;

    for (const syncData of allSyncData) {
      try {
        // 检查是否已经生成过
        const existing = await PreGeneratedPlan.findOne({ userId: syncData.userId, date: targetDate });
        if (existing) {
          skipCount++;
          continue;
        }

        const pendingTasks = this.filterPendingTasks(syncData.tasks || []);
        if (pendingTasks.length === 0) {
          skipCount++;
          continue;
        }

        // 去重
        const dedupedTasks = this.deduplicateTasks(pendingTasks);

        // 构建 summary
        const summaryList = dedupedTasks.map(t => ({
          id: t.id,
          title: t.title,
          isImportant: t.isImportant || false,
          priority: t.priority || 'normal',
          category: t.category || '',
          dueDate: t.dueDate ? getShanghaiDateString(new Date(t.dueDate)) : 'no_deadline',
          isDueToday: t.dueDate ? getShanghaiDateString(new Date(t.dueDate)) === targetDate : false,
          isOverdue: t.dueDate ? t.dueDate < Date.now() && t.status !== 'completed' : false,
          estimatedHours: t.estimatedHours || 0.5,
          isRecurring: t.isReminderAutoGenerated || false
        }));

        // 调用 AI
        const pendingCount = summaryList.length;
        let planData = await this.callAI(JSON.stringify(summaryList), pendingCount);

        if (planData && planData.focusTasks) {
          planData = this.keepTodayCommittedTasks(planData, summaryList, 14, targetDate);

          // 过滤捏造的 ID
          const validIds = new Set(pendingTasks.map(t => t.id));
          planData.focusTasks = planData.focusTasks.filter(item => validIds.has(item.id));
          planData.deferTasks = (planData.deferTasks || []).filter(id => validIds.has(id));

          // 存入数据库
          await PreGeneratedPlan.findOneAndUpdate(
            { userId: syncData.userId, date: targetDate },
            {
              userId: syncData.userId,
              date: targetDate,
              planData: planData,
              taskSnapshot: summaryList,
              generatedAt: Date.now(),
              status: 'pending'
            },
            { upsert: true, new: true }
          );
          successCount++;
          console.log(`[PlanScheduler] 用户 ${syncData.userId} 计划生成完成`);
        } else {
          errorCount++;
          console.warn(`[PlanScheduler] 用户 ${syncData.userId} AI返回无效结果`);
        }

        // 每个用户之间间隔1秒，避免API限流
        await this.sleep(1000);
      } catch (error) {
        errorCount++;
        console.error(`[PlanScheduler] 用户 ${syncData.userId} 生成失败:`, error.message);
      }
    }

    console.log(`[PlanScheduler] 批量生成完成: 成功=${successCount}, 跳过=${skipCount}, 失败=${errorCount}`);
  }

  /**
   * 筛选待办任务
   */
  filterPendingTasks(tasks) {
    return tasks.filter(t => t.status === 'pending');
  }

  /**
   * 去重：同一个 reminderId 只保留 dueDate 最近的一条
   */
  deduplicateTasks(tasks) {
    const reminderGroups = new Map();
    const result = [];

    for (const task of tasks) {
      if (task.isReminderAutoGenerated && task.reminderId) {
        const group = reminderGroups.get(task.reminderId) || [];
        group.push(task);
        reminderGroups.set(task.reminderId, group);
      } else {
        result.push(task);
      }
    }

    // 每组取最近的一条
    for (const [, group] of reminderGroups) {
      group.sort((a, b) => {
        const aDate = a.dueDate || 0;
        const bDate = b.dueDate || 0;
        return Math.abs(aDate - Date.now()) - Math.abs(bDate - Date.now());
      });
      result.push(group[0]);
    }

    return result;
  }

  /**
   * 调用百炼 AI 生成计划
   */
  async callAI(pendingTasksSummary, pendingCount) {
    if (!this.appId || !this.apiKey) {
      console.error('[PlanScheduler] 百炼 API Key 或 App ID 未配置');
      return null;
    }

    const currentHour = 3; // 基于凌晨时段的默认预估
    const remainingHours = 14;
    const todayDate = getShanghaiDateString();
    const overloadThresholdHours = Math.max(remainingHours * 1.4, remainingHours + 4);
    let todayCommittedCount = 0;
    let todayCommittedHours = 0;
    let totalEstimatedHours = 0;
    try {
      const parsed = JSON.parse(pendingTasksSummary);
      if (Array.isArray(parsed)) {
        parsed.forEach((task) => {
          const estimatedHours = task && task.estimatedHours > 0 ? task.estimatedHours : 0.5;
          totalEstimatedHours += estimatedHours;
          if (task && (task.isOverdue === true || task.isDueToday === true || task.dueDate === todayDate)) {
            todayCommittedCount += 1;
            todayCommittedHours += estimatedHours;
          }
        });
      }
    } catch (_) {}

    const prompt = `
你是一个精益时间管理专家。请根据用户的今日待办（包含 dueDate、isOverdue 和预估耗时 estimatedHours 等维度信息）的 JSON 汇总，为他制定一份【今日行动计划】。

要求：
1. 默认策略是尊重用户既定安排：凡是已经安排在今天的任务，应尽量纳入 \`focusTasks\`，除非今日负荷已经明显超出正常人可完成的程度。
2. 当前待办共 ${pendingCount} 项，预计总量约 ${totalEstimatedHours.toFixed(1)} 小时；其中用户已经安排在今天或已逾期的任务共 ${todayCommittedCount} 项，约 ${todayCommittedHours.toFixed(1)} 小时。
3. 凡是 \`isDueToday=true\`、\`dueDate="${todayDate}"\` 或 \`isOverdue=true\` 的任务，都视为用户今天已经明确安排或必须今天处理的任务。默认应尽量把这部分任务纳入 \`focusTasks\`，不要机械压缩到固定 2~6 项。
4. 只有当“今天已安排/已逾期任务”已经明显超载时，才允许主动缩减。这里“明显超载”指任务总负荷已经远超正常人今天可完成的程度，例如超过剩余可用时间的约 1.4 倍（当前阈值约 ${overloadThresholdHours.toFixed(1)} 小时），或者任务数量已经显著不现实。
5. 如果今天已安排任务没有明显超载，\`focusTasks\` 应优先完整覆盖这些任务；只有在仍有带宽时，才补充无日期或可弹性安排的任务。缩减时优先保留：已逾期 > 今天到期/今天安排 > 高优任务 > 其他任务。
6. \`focusTasks\` 必须补充 \`reason\`（简短一句话说明为什么优先，例如"因为今天到期"或"高优且已逾期"）。
7. \`groupedTasks\` 必须将所有的 \`focusTasks\` 中的任务 ID 进行科学的人性化分组归类（例如："深度工作"、"碎片处理"、"沟通协作"、"出门顺手做"等）。
8. 对于剩余的不重要或精力不足可以推迟的任务，提炼其 taskId 放入 \`deferTasks\`，建议推迟释放今日带宽。若今天已安排任务未超载，优先把没有明确今天约束的任务放入 \`deferTasks\`。
9. \`summary\` 给出今天的简练总结（包含今天的建议基准和负荷评估）。禁止发散不定期的废话。
10. 标注了 "isRecurring": true 的任务来自周期性重复提醒（如每日习惯打卡），同一类重复任务每天最多安排一次，绝不可将多个标题相似的重复任务同时放入 focusTasks。如果存在多个标题高度相似的任务（如"背单词"与"背单词"），只保留一个在 focusTasks，其余放入 deferTasks。
11. 【非常重要】作为预生成计划，我们假设用户今天有充沛的可用带宽（至少 ${remainingHours} 小时可用）。制定计划时，\`focusTasks\` 的任务总预估耗时 (totalEstimatedHours) 必须 **严格小于等于** ${remainingHours} 小时。确保工作量饱满且可行；但也不要在任务并未明显超载时，随意删减用户今天已安排好的事项。

严格输出纯 JSON 格式：
{
  "focusTasks": [
    { "id": "taskId_1", "reason": "高优项且今日必须交付" },
    { "id": "taskId_2", "reason": "已逾期需尽快收尾" }
  ],
  "groupedTasks": {
    "深度工作": ["taskId_1"],
    "碎片处理": ["taskId_2"]
  },
  "deferTasks": ["taskId_3", "taskId_4"],
  "summary": "今天主要收尾两个项目文档，约需2.5小时可以搞定。杂项已推迟。",
  "totalEstimatedHours": 2.5
}

今日待办池信息：
${pendingTasksSummary}
`;

    try {
      const response = await axios.post(
        `https://dashscope.aliyuncs.com/api/v1/apps/${this.appId}/completion`,
        {
          input: { prompt: prompt }
        },
        {
          headers: {
            'Authorization': `Bearer ${this.apiKey}`,
            'Content-Type': 'application/json'
          },
          timeout: 120000 // 2分钟超时
        }
      );

      const text = response.data?.output?.text;
      if (!text) return null;

      // 清理 markdown 代码块
      let cleaned = text.replace(/```json\s*/g, '').replace(/```\s*/g, '').trim();
      return JSON.parse(cleaned);
    } catch (error) {
      console.error('[PlanScheduler] AI调用失败:', error.message);
      return null;
    }
  }

  sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  getEstimatedHours(task) {
    return task && task.estimatedHours > 0 ? task.estimatedHours : 0.5;
  }

  isTodayCommittedTask(task, targetDate) {
    return !!(task && (task.isOverdue === true || task.isDueToday === true || task.dueDate === targetDate));
  }

  keepTodayCommittedTasks(planData, summaryList, remainingHours, targetDate) {
    const committedTasks = summaryList.filter(task => this.isTodayCommittedTask(task, targetDate));
    const overloadThresholdHours = Math.max(remainingHours * 1.4, remainingHours + 4);
    const committedHours = committedTasks.reduce((sum, task) => sum + this.getEstimatedHours(task), 0);
    if (committedTasks.length === 0 || committedHours > overloadThresholdHours) {
      return planData;
    }

    const focusTasks = Array.isArray(planData.focusTasks) ? [...planData.focusTasks] : [];
    const focusIds = new Set(focusTasks.map(item => item.id));
    let addedCount = 0;
    committedTasks.forEach((task) => {
      if (focusIds.has(task.id)) {
        return;
      }
      focusTasks.push({
        id: task.id,
        reason: task.isOverdue ? '已逾期且今天必须处理，默认保留在今日计划中' : '用户已安排在今天，默认保留在今日计划中'
      });
      focusIds.add(task.id);
      addedCount += 1;
    });

    if (addedCount === 0) {
      return planData;
    }

    const summaryMap = new Map(summaryList.map(task => [task.id, task]));
    const totalEstimatedHours = focusTasks.reduce((sum, item) => {
      return sum + this.getEstimatedHours(summaryMap.get(item.id));
    }, 0);
    const nextGroupedTasks = planData.groupedTasks && typeof planData.groupedTasks === 'object'
      ? { ...planData.groupedTasks }
      : undefined;
    if (nextGroupedTasks) {
      const key = '今天已安排';
      const existingIds = Array.isArray(nextGroupedTasks[key]) ? nextGroupedTasks[key] : [];
      committedTasks.forEach((task) => {
        if (focusIds.has(task.id) && !existingIds.includes(task.id)) {
          existingIds.push(task.id);
        }
      });
      nextGroupedTasks[key] = existingIds;
    }

    return {
      ...planData,
      focusTasks,
      deferTasks: Array.isArray(planData.deferTasks) ? planData.deferTasks.filter(id => !focusIds.has(id)) : [],
      groupedTasks: nextGroupedTasks,
      totalEstimatedHours
    };
  }
}

module.exports = PlanScheduler;
